# https://eslint.org/docs/latest/rules

extends: eslint:recommended

env:
  browser: true
  node: true
  es2021: true

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  eqeqeq: off
  semi: error
  curly: error
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  no-undef: error
  no-console: error
  no-unused-vars: error

ignorePatterns:
  - node_modules/
